# Generated by Django 3.1.4 on 2021-01-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('address_building', models.CharField(blank=True, max_length=50, verbose_name='Building Name/Number')),
                ('address_street', models.CharField(blank=True, max_length=50, verbose_name='Street')),
                ('address_town', models.CharField(blank=True, max_length=50, verbose_name='Town')),
                ('address_county', models.CharField(blank=True, max_length=50, verbose_name='County')),
                ('address_postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('telephone_number', models.CharField(max_length=25, verbose_name='Telephone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('preferred_time_to_call', models.CharField(choices=[('M', '9am - 12pm (Mon-Fri)'), ('EA', '12pm - 3pm (Mon-Fri)'), ('LA', '3pm - 5pm (Mon-Fri)'), ('S', '9am - 2pm (Sat)')], default='M', max_length=2, verbose_name='Preferred Time to Call')),
                ('annual_income', models.IntegerField(verbose_name='Annual Income')),
                ('loan_amount', models.IntegerField(verbose_name='Loan Amount')),
                ('property_value', models.IntegerField(verbose_name='Property Value')),
                ('mortgage_type', models.CharField(choices=[('NH', 'New House'), ('RM', 'Remortgage')], default='NH', max_length=2, verbose_name='Mortgage Type')),
            ],
        ),
    ]
