# Generated by Django 3.1.4 on 2021-01-10 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=50, verbose_name='Building and Street'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_been_contacted',
            field=models.BooleanField(default=False, verbose_name='Has been Contacted?'),
        ),
    ]
