# Generated by Django 3.1.4 on 2021-01-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210110_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(verbose_name='Date Created'),
        ),
    ]
